package sudoku_Final;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Totoros
 */
public class Duidoku extends javax.swing.JDialog implements GameBoard{

    /**
     * Creates new form Duidoku
     */
    public Duidoku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    @Override
    public void newGame(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board = new javax.swing.JPanel();
        block11 = new javax.swing.JPanel();
        cell11 = new javax.swing.JLabel();
        cell12 = new javax.swing.JLabel();
        cell21 = new javax.swing.JLabel();
        cell22 = new javax.swing.JLabel();
        block12 = new javax.swing.JPanel();
        cell13 = new javax.swing.JLabel();
        cell14 = new javax.swing.JLabel();
        cell23 = new javax.swing.JLabel();
        cell24 = new javax.swing.JLabel();
        block21 = new javax.swing.JPanel();
        cell31 = new javax.swing.JLabel();
        cell32 = new javax.swing.JLabel();
        cell41 = new javax.swing.JLabel();
        cell42 = new javax.swing.JLabel();
        block22 = new javax.swing.JPanel();
        cell33 = new javax.swing.JLabel();
        cell34 = new javax.swing.JLabel();
        cell43 = new javax.swing.JLabel();
        cell44 = new javax.swing.JLabel();
        statistics = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("duidoku");

        board.setBorder(new javax.swing.border.MatteBorder(null));
        board.setLayout(new java.awt.GridLayout(2, 2, 2, 2));

        block11.setBorder(new javax.swing.border.MatteBorder(null));
        block11.setMinimumSize(new java.awt.Dimension(2, 2));
        block11.setPreferredSize(new java.awt.Dimension(2, 2));
        block11.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        cell11.setBackground(new java.awt.Color(255, 255, 255));
        cell11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell11.setMaximumSize(new java.awt.Dimension(50, 50));
        cell11.setMinimumSize(new java.awt.Dimension(50, 50));
        cell11.setOpaque(true);
        cell11.setPreferredSize(new java.awt.Dimension(50, 50));
        block11.add(cell11);

        cell12.setBackground(new java.awt.Color(255, 255, 255));
        cell12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell12.setMaximumSize(new java.awt.Dimension(50, 50));
        cell12.setMinimumSize(new java.awt.Dimension(50, 50));
        cell12.setOpaque(true);
        cell12.setPreferredSize(new java.awt.Dimension(50, 50));
        block11.add(cell12);

        cell21.setBackground(new java.awt.Color(255, 255, 255));
        cell21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell21.setMaximumSize(new java.awt.Dimension(50, 50));
        cell21.setMinimumSize(new java.awt.Dimension(50, 50));
        cell21.setOpaque(true);
        cell21.setPreferredSize(new java.awt.Dimension(50, 50));
        block11.add(cell21);

        cell22.setBackground(new java.awt.Color(255, 255, 255));
        cell22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell22.setMaximumSize(new java.awt.Dimension(50, 50));
        cell22.setMinimumSize(new java.awt.Dimension(50, 50));
        cell22.setOpaque(true);
        cell22.setPreferredSize(new java.awt.Dimension(50, 50));
        block11.add(cell22);

        board.add(block11);

        block12.setBorder(new javax.swing.border.MatteBorder(null));
        block12.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        cell13.setBackground(new java.awt.Color(255, 255, 255));
        cell13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell13.setMaximumSize(new java.awt.Dimension(50, 50));
        cell13.setMinimumSize(new java.awt.Dimension(50, 50));
        cell13.setOpaque(true);
        cell13.setPreferredSize(new java.awt.Dimension(50, 50));
        block12.add(cell13);

        cell14.setBackground(new java.awt.Color(255, 255, 255));
        cell14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell14.setMaximumSize(new java.awt.Dimension(50, 50));
        cell14.setMinimumSize(new java.awt.Dimension(50, 50));
        cell14.setOpaque(true);
        cell14.setPreferredSize(new java.awt.Dimension(50, 50));
        block12.add(cell14);

        cell23.setBackground(new java.awt.Color(255, 255, 255));
        cell23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell23.setMaximumSize(new java.awt.Dimension(50, 50));
        cell23.setMinimumSize(new java.awt.Dimension(50, 50));
        cell23.setOpaque(true);
        cell23.setPreferredSize(new java.awt.Dimension(50, 50));
        block12.add(cell23);

        cell24.setBackground(new java.awt.Color(255, 255, 255));
        cell24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell24.setMaximumSize(new java.awt.Dimension(50, 50));
        cell24.setMinimumSize(new java.awt.Dimension(50, 50));
        cell24.setOpaque(true);
        cell24.setPreferredSize(new java.awt.Dimension(50, 50));
        block12.add(cell24);

        board.add(block12);

        block21.setBorder(new javax.swing.border.MatteBorder(null));
        block21.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        cell31.setBackground(new java.awt.Color(255, 255, 255));
        cell31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell31.setMaximumSize(new java.awt.Dimension(50, 50));
        cell31.setMinimumSize(new java.awt.Dimension(50, 50));
        cell31.setOpaque(true);
        cell31.setPreferredSize(new java.awt.Dimension(50, 50));
        block21.add(cell31);

        cell32.setBackground(new java.awt.Color(255, 255, 255));
        cell32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell32.setMaximumSize(new java.awt.Dimension(50, 50));
        cell32.setMinimumSize(new java.awt.Dimension(50, 50));
        cell32.setOpaque(true);
        cell32.setPreferredSize(new java.awt.Dimension(50, 50));
        block21.add(cell32);

        cell41.setBackground(new java.awt.Color(255, 255, 255));
        cell41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell41.setMaximumSize(new java.awt.Dimension(50, 50));
        cell41.setMinimumSize(new java.awt.Dimension(50, 50));
        cell41.setOpaque(true);
        cell41.setPreferredSize(new java.awt.Dimension(50, 50));
        block21.add(cell41);

        cell42.setBackground(new java.awt.Color(255, 255, 255));
        cell42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell42.setMaximumSize(new java.awt.Dimension(50, 50));
        cell42.setMinimumSize(new java.awt.Dimension(50, 50));
        cell42.setOpaque(true);
        cell42.setPreferredSize(new java.awt.Dimension(50, 50));
        block21.add(cell42);

        board.add(block21);

        block22.setBorder(new javax.swing.border.MatteBorder(null));
        block22.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        cell33.setBackground(new java.awt.Color(255, 255, 255));
        cell33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell33.setMaximumSize(new java.awt.Dimension(50, 50));
        cell33.setMinimumSize(new java.awt.Dimension(50, 50));
        cell33.setOpaque(true);
        cell33.setPreferredSize(new java.awt.Dimension(50, 50));
        block22.add(cell33);

        cell34.setBackground(new java.awt.Color(255, 255, 255));
        cell34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell34.setMaximumSize(new java.awt.Dimension(50, 50));
        cell34.setMinimumSize(new java.awt.Dimension(50, 50));
        cell34.setOpaque(true);
        cell34.setPreferredSize(new java.awt.Dimension(50, 50));
        block22.add(cell34);

        cell43.setBackground(new java.awt.Color(255, 255, 255));
        cell43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell43.setMaximumSize(new java.awt.Dimension(50, 50));
        cell43.setMinimumSize(new java.awt.Dimension(50, 50));
        cell43.setOpaque(true);
        cell43.setPreferredSize(new java.awt.Dimension(50, 50));
        block22.add(cell43);

        cell44.setBackground(new java.awt.Color(255, 255, 255));
        cell44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cell44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell44.setMaximumSize(new java.awt.Dimension(50, 50));
        cell44.setMinimumSize(new java.awt.Dimension(50, 50));
        cell44.setOpaque(true);
        cell44.setPreferredSize(new java.awt.Dimension(50, 50));
        block22.add(cell44);

        board.add(block22);

        statistics.setText("Statistics");
        statistics.setPreferredSize(new java.awt.Dimension(40, 40));

        exit.setText("Exit");
        exit.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("1");
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("2");
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.setRequestFocusEnabled(false);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("3");
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.setRequestFocusEnabled(false);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("4");
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton4.setRequestFocusEnabled(false);

        help.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        help.setText("Help");
        help.setPreferredSize(new java.awt.Dimension(40, 40));
        help.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statistics, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(statistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Duidoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Duidoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Duidoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Duidoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Duidoku dialog = new Duidoku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel block11;
    private javax.swing.JPanel block12;
    private javax.swing.JPanel block21;
    private javax.swing.JPanel block22;
    private javax.swing.JPanel board;
    private javax.swing.JLabel cell11;
    private javax.swing.JLabel cell12;
    private javax.swing.JLabel cell13;
    private javax.swing.JLabel cell14;
    private javax.swing.JLabel cell21;
    private javax.swing.JLabel cell22;
    private javax.swing.JLabel cell23;
    private javax.swing.JLabel cell24;
    private javax.swing.JLabel cell31;
    private javax.swing.JLabel cell32;
    private javax.swing.JLabel cell33;
    private javax.swing.JLabel cell34;
    private javax.swing.JLabel cell41;
    private javax.swing.JLabel cell42;
    private javax.swing.JLabel cell43;
    private javax.swing.JLabel cell44;
    private javax.swing.JButton exit;
    private javax.swing.JButton help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton statistics;
    // End of variables declaration//GEN-END:variables
}
